[package]
name = "cargo-bom"
version = "0.2.1"
authors = [ "Ossi Herrala <oherrala@iki.fi>" ]
license = "MIT"

description = "Bill of Materials for Rust Crates"
homepage = "https://github.com/sensorfu/cargo-bom#readme"
repository = "https://github.com/sensorfu/cargo-bom"
readme = "README.md"

categories = ["command-line-utilities", "development-tools", "development-tools::cargo-plugins"]
keywords = ["bom", "bill-of-materials", "ingredients", "dependencies", "deps"]

[badges]
circle-ci = { repository = "sensorfu/cargo-bom", branch = "master" }

[profile.release]
lto = true

[dependencies]
cargo = "0.23.0"
serde = "1.0.17"
serde_derive = "1.0.17"
tabwriter = "1.0.3"
