version: 2
jobs:
  build:
    docker:
      - image: rust:latest
    steps:
      - checkout
      - run:
          name: install_deps
          command: |
            apt -y update
            apt -y install cmake
      - run:
          name: install_rust_toolchains
          command: |
            rustup update
            rustup component add clippy-preview
            rustup install beta
            rustup install nightly
      - run: cargo test
      - run: cargo clippy
      - run: cargo +beta test
      - run: cargo +nightly test
